### ISSUE TITLE
Landmark::GetItem and GetTile Performance

### ISSUE THREAD

**Issue by essial** [HarvestRogue/harvest-rogue#18]
Currently Landmark::GetItem uses up to 45% of all processing time, and 20% for GetTile on any given cycle. This is due to the number of calls vs the relatively slow lookup time for maps and vectors.

**Comment by essial** [comment]
We may just need to create a width*height array of std::shared_ptr objects. Sounds brute force, but if the memory impact isn't too great, the speedup will be worth it.

**Comment by LunaticEdit** [comment]
GetTileType was optimized and no longer uses vectors.
