### ISSUE TITLE
Containers

### ISSUE THREAD

**Issue by essial** [HarvestRogue/harvest-rogue#22]
We need to create a **Contaner** interface, UI for interacting with it, as well as **Chest** and **Bag** items to the game with these attributes. This will be necessary before crafting can be fully implemented.

It is _highly_ recommended that an `IContainer` interface is used and implemented for both the player object, as well as the Container interface. Given that the UI needs to allow movement from one place to another, doing it with IContainer instead of Player<->Container explicitly will make the system much more dynamic for future updates.

**Comment by LunaticEdit** [comment]
Closed with #30
